on dosave
  global saveA, saveB, saveC, saveD, saveE, saveF, saveG, saveNum, inexits, meetings, nof, saveH, TIMEKEEPER, clockspeed, newansglobal, timeguide, globaljokes, wreck, firsttalk, shelltoday, mirror, sink, bath, realcards, catgame, DorN, cdsavepath, monk, guard, dubi, globalnight, foe, afganicnt, globalday, savei, savepath
  put nof into field ("nof" & saveNum)
  put saveA into field ("gamename" & saveNum)
  put saveB into field ("clickoncharacter" & saveNum)
  put saveC into field ("objectsfield" & saveNum)
  put saveD into field ("afganifield" & saveNum)
  put saveE into field ("plane" & saveNum)
  put saveF into field ("points" & saveNum)
  put globalday into field ("whichday" & saveNum)
  put inexits into field ("inexits" & saveNum)
  put meetings into field ("meetings" & saveNum)
  put foe into field ("foe" & saveNum)
  put saveG into field ("globaljokes" & saveNum)
  put afganicnt into field ("afganicnt" & saveNum)
  put wreck into field ("wreck" & saveNum)
  put firsttalk into field ("firsttalk" & saveNum)
  put shelltoday into field ("shelltoday" & saveNum)
  put mirror into field ("mirror" & saveNum)
  put sink into field ("sink" & saveNum)
  put bath into field ("bath" & saveNum)
  put globalday into field ("globalday" & saveNum)
  put monk into field ("monk" & saveNum)
  put guard into field ("guard" & saveNum)
  put dubi into field ("dubi" & saveNum)
  put DorN into field ("DorN" & saveNum)
  put savei into field ("savei" & saveNum)
  put globalnight into field ("globalnight" & saveNum)
  put saveH into field ("saveH" & saveNum)
  put catgame into field ("catgame" & saveNum)
  saveMovie(savepath & "hezsave.dir")
  go("aftersave", cdsavepath & "saveload.dxr")
end
