on doload
  global saveA, saveB, saveC, saveD, saveE, saveG, saveNum, saveF, inexits, meetings, GlobalHour, GlobalSecond, nof, TIMEKEEPER, clockspeed, newansglobal, timeguide, globaljokes, wreck, saveH, firsttalk, shelltoday, mirror, sink, bath, realcards, catgame, DorN, cdsavepath, monk, guard, dubi, globalnight, foe, afganicnt, globalday, savei
  nof = field("nof" & saveNum)
  saveB = field("clickoncharacter" & saveNum)
  saveC = field("objectsfield" & saveNum)
  saveD = field("afganifield" & saveNum)
  saveE = field("plane" & saveNum)
  saveF = field("points" & saveNum)
  globalday = value(field("whichday" & saveNum))
  inexits = field("inexits" & saveNum)
  meetings = field("meetings" & saveNum)
  foe = field("foe" & saveNum)
  DorN = field("DorN" & saveNum)
  savei = field("savei" & saveNum)
  saveG = field("globaljokes" & saveNum)
  afganicnt = field("afganicnt" & saveNum)
  wreck = field("wreck" & saveNum)
  firsttalk = field("firsttalk" & saveNum)
  shelltoday = field("shelltoday" & saveNum)
  mirror = field("mirror" & saveNum)
  sink = field("sink" & saveNum)
  bath = field("bath" & saveNum)
  globalday = value(field("globalday" & saveNum))
  globalnight = field("globalnight" & saveNum)
  catgame = value(field("catgame" & saveNum))
  monk = field("monk" & saveNum)
  guard = field("guard" & saveNum)
  dubi = field("dubi" & saveNum)
  saveH = field("saveH" & saveNum)
  go("afterload", cdsavepath & "saveload.dxr")
end
