extends RefCounted
## `the <entity> of <target>` as compiled Lingo encodes it: bank, field, and what
## else the opcode pops.
##
## **Generated by `tools/gen_lscr_the_table.py` -- do not edit by hand.** The 145
## rows are `lingoV4TheEntity[]` from
## `reference/scummvm/lingo/lingo-bytecode.cpp`, joined against the entity and
## field name tables in `lingo-the.cpp` so the enum constants come back out as
## the Lingo words they stand for. `docs/LSCR_FORMAT.md` section 4.3 says of this
## table, in those words, "Do not retype it".
##
## `get` (0x5c) and `set` (0x5d) carry a **bank** as their operand; the *first
## argument on the stack* selects the field within the bank. So the key here is
## `(bank << 8) | firstArg`, which is how the reference keys it too.
##
## `args` says what the opcode pops besides that selector, and it is the only
## part of a row that changes the shape of the decode rather than the name in it:
##
## | `args` | popped |
## | --- | --- |
## | `none` | nothing |
## | `id` | an id (`the castNum of sprite 3`) -- and at D5+, for `the cast` and `the field`, an id **and** a cast-lib id |
## | `string` | a string (`the last word of "..."`) |
## | `menu` / `menuitem` | a menu id, and an item id for the pair |
## | `chunk` | a chunk expression |
##
## The regenerate step is `python tools/gen_lscr_the_table.py` after
## `bash tools/fetch_scummvm_reference.sh`. The file is committed because
## `reference/` is fetched rather than tracked, and a fresh checkout has to be
## able to run the decoder without it.

## `(bank << 8) | firstArg` -> `{entity, field, writable, args}`.
const ROWS := {
	0x0000: {"entity": "floatPrecision", "field": "", "writable": true, "args": "none"},
	0x0001: {"entity": "mouseDownScript", "field": "", "writable": true, "args": "none"},
	0x0002: {"entity": "mouseUpScript", "field": "", "writable": true, "args": "none"},
	0x0003: {"entity": "keyDownScript", "field": "", "writable": true, "args": "none"},
	0x0004: {"entity": "keyUpScript", "field": "", "writable": true, "args": "none"},
	0x0005: {"entity": "timeoutScript", "field": "", "writable": true, "args": "none"},
	0x0006: {"entity": "time", "field": "short", "writable": false, "args": "none"},
	0x0007: {"entity": "time", "field": "abbreviated", "writable": false, "args": "none"},
	0x0008: {"entity": "time", "field": "long", "writable": false, "args": "none"},
	0x0009: {"entity": "date", "field": "short", "writable": false, "args": "none"},
	0x000A: {"entity": "date", "field": "abbreviated", "writable": false, "args": "none"},
	0x000B: {"entity": "date", "field": "long", "writable": false, "args": "none"},
	0x000C: {"entity": "chars", "field": "last", "writable": false, "args": "string"},
	0x000D: {"entity": "words", "field": "last", "writable": false, "args": "string"},
	0x000E: {"entity": "items", "field": "last", "writable": false, "args": "string"},
	0x000F: {"entity": "lines", "field": "last", "writable": false, "args": "string"},
	0x0101: {"entity": "chars", "field": "number", "writable": false, "args": "string"},
	0x0102: {"entity": "words", "field": "number", "writable": false, "args": "string"},
	0x0103: {"entity": "items", "field": "number", "writable": false, "args": "string"},
	0x0104: {"entity": "lines", "field": "number", "writable": false, "args": "string"},
	0x0201: {"entity": "menu", "field": "name", "writable": false, "args": "menu"},
	0x0202: {"entity": "menuitems", "field": "number", "writable": false, "args": "menu"},
	0x0301: {"entity": "menuitem", "field": "name", "writable": true, "args": "menuitem"},
	0x0302: {"entity": "menuitem", "field": "checkmark", "writable": true, "args": "menuitem"},
	0x0303: {"entity": "menuitem", "field": "enabled", "writable": true, "args": "menuitem"},
	0x0304: {"entity": "menuitem", "field": "script", "writable": true, "args": "menuitem"},
	0x0401: {"entity": "sound", "field": "volume", "writable": true, "args": "id"},
	0x0601: {"entity": "sprite", "field": "type", "writable": true, "args": "id"},
	0x0602: {"entity": "sprite", "field": "backColor", "writable": true, "args": "id"},
	0x0603: {"entity": "sprite", "field": "bottom", "writable": true, "args": "id"},
	0x0604: {"entity": "sprite", "field": "castNum", "writable": true, "args": "id"},
	0x0605: {"entity": "sprite", "field": "constraint", "writable": true, "args": "id"},
	0x0606: {"entity": "sprite", "field": "cursor", "writable": true, "args": "id"},
	0x0607: {"entity": "sprite", "field": "foreColor", "writable": true, "args": "id"},
	0x0608: {"entity": "sprite", "field": "height", "writable": true, "args": "id"},
	0x0609: {"entity": "sprite", "field": "immediate", "writable": true, "args": "id"},
	0x060A: {"entity": "sprite", "field": "ink", "writable": true, "args": "id"},
	0x060B: {"entity": "sprite", "field": "left", "writable": true, "args": "id"},
	0x060C: {"entity": "sprite", "field": "lineSize", "writable": true, "args": "id"},
	0x060D: {"entity": "sprite", "field": "locH", "writable": true, "args": "id"},
	0x060E: {"entity": "sprite", "field": "locV", "writable": true, "args": "id"},
	0x060F: {"entity": "sprite", "field": "movieRate", "writable": true, "args": "id"},
	0x0610: {"entity": "sprite", "field": "movieTime", "writable": true, "args": "id"},
	0x0611: {"entity": "sprite", "field": "pattern", "writable": true, "args": "id"},
	0x0612: {"entity": "sprite", "field": "puppet", "writable": true, "args": "id"},
	0x0613: {"entity": "sprite", "field": "right", "writable": true, "args": "id"},
	0x0614: {"entity": "sprite", "field": "startTime", "writable": true, "args": "id"},
	0x0615: {"entity": "sprite", "field": "stopTime", "writable": true, "args": "id"},
	0x0616: {"entity": "sprite", "field": "stretch", "writable": true, "args": "id"},
	0x0617: {"entity": "sprite", "field": "top", "writable": true, "args": "id"},
	0x0618: {"entity": "sprite", "field": "trails", "writable": true, "args": "id"},
	0x0619: {"entity": "sprite", "field": "visible", "writable": true, "args": "id"},
	0x061A: {"entity": "sprite", "field": "volume", "writable": true, "args": "id"},
	0x061B: {"entity": "sprite", "field": "width", "writable": true, "args": "id"},
	0x061C: {"entity": "sprite", "field": "blend", "writable": true, "args": "id"},
	0x061D: {"entity": "sprite", "field": "scriptNum", "writable": true, "args": "id"},
	0x061E: {"entity": "sprite", "field": "moveableSprite", "writable": true, "args": "id"},
	0x061F: {"entity": "sprite", "field": "editableText", "writable": true, "args": "id"},
	0x0620: {"entity": "sprite", "field": "scoreColor", "writable": true, "args": "id"},
	0x0621: {"entity": "sprite", "field": "loc", "writable": true, "args": "id"},
	0x0622: {"entity": "sprite", "field": "rect", "writable": true, "args": "id"},
	0x0623: {"entity": "sprite", "field": "memberNum", "writable": true, "args": "id"},
	0x0624: {"entity": "sprite", "field": "castLibNum", "writable": true, "args": "id"},
	0x0625: {"entity": "sprite", "field": "member", "writable": true, "args": "id"},
	0x0626: {"entity": "sprite", "field": "scriptInstanceList", "writable": true, "args": "id"},
	0x0627: {"entity": "sprite", "field": "currentTime", "writable": true, "args": "id"},
	0x0628: {"entity": "sprite", "field": "mostRecentCuePoint", "writable": true, "args": "id"},
	0x0629: {"entity": "sprite", "field": "tweened", "writable": true, "args": "id"},
	0x062A: {"entity": "sprite", "field": "name", "writable": true, "args": "id"},
	0x0701: {"entity": "beepOn", "field": "", "writable": true, "args": "none"},
	0x0702: {"entity": "buttonStyle", "field": "", "writable": true, "args": "none"},
	0x0703: {"entity": "centerStage", "field": "", "writable": true, "args": "none"},
	0x0704: {"entity": "checkBoxAccess", "field": "", "writable": true, "args": "none"},
	0x0705: {"entity": "checkBoxType", "field": "", "writable": true, "args": "none"},
	0x0706: {"entity": "colorDepth", "field": "", "writable": true, "args": "none"},
	0x0707: {"entity": "colorQD", "field": "", "writable": true, "args": "none"},
	0x0708: {"entity": "exitLock", "field": "", "writable": true, "args": "none"},
	0x0709: {"entity": "fixStageSize", "field": "", "writable": true, "args": "none"},
	0x070A: {"entity": "fullColorPermit", "field": "", "writable": true, "args": "none"},
	0x070B: {"entity": "imageDirect", "field": "", "writable": true, "args": "none"},
	0x070C: {"entity": "doubleClick", "field": "", "writable": true, "args": "none"},
	0x070E: {"entity": "lastClick", "field": "", "writable": true, "args": "none"},
	0x070F: {"entity": "lastEvent", "field": "", "writable": true, "args": "none"},
	0x0711: {"entity": "lastKey", "field": "", "writable": true, "args": "none"},
	0x0712: {"entity": "lastRoll", "field": "", "writable": true, "args": "none"},
	0x0713: {"entity": "timeoutLapsed", "field": "", "writable": true, "args": "none"},
	0x0714: {"entity": "multiSound", "field": "", "writable": true, "args": "none"},
	0x0715: {"entity": "pauseState", "field": "", "writable": true, "args": "none"},
	0x0716: {"entity": "quickTimePresent", "field": "", "writable": true, "args": "none"},
	0x0717: {"entity": "selEnd", "field": "", "writable": true, "args": "none"},
	0x0718: {"entity": "selStart", "field": "", "writable": true, "args": "none"},
	0x0719: {"entity": "soundEnabled", "field": "", "writable": true, "args": "none"},
	0x071A: {"entity": "soundLevel", "field": "", "writable": true, "args": "none"},
	0x071B: {"entity": "stageColor", "field": "", "writable": true, "args": "none"},
	0x071D: {"entity": "switchColorDepth", "field": "", "writable": true, "args": "none"},
	0x071E: {"entity": "timeoutKeyDown", "field": "", "writable": true, "args": "none"},
	0x071F: {"entity": "timeoutLength", "field": "", "writable": true, "args": "none"},
	0x0720: {"entity": "timeoutMouse", "field": "", "writable": true, "args": "none"},
	0x0721: {"entity": "timeoutPlay", "field": "", "writable": true, "args": "none"},
	0x0722: {"entity": "timer", "field": "", "writable": true, "args": "none"},
	0x0723: {"entity": "preLoadRAM", "field": "", "writable": true, "args": "none"},
	0x0724: {"entity": "videoForWindowsPresent", "field": "", "writable": true, "args": "none"},
	0x0801: {"entity": "perFrameHook", "field": "", "writable": true, "args": "none"},
	0x0802: {"entity": "castmembers", "field": "number", "writable": false, "args": "none"},
	0x0803: {"entity": "menus", "field": "number", "writable": false, "args": "none"},
	0x0804: {"entity": "castLibs", "field": "number", "writable": false, "args": "none"},
	0x0805: {"entity": "xtras", "field": "number", "writable": false, "args": "none"},
	0x0901: {"entity": "cast", "field": "name", "writable": true, "args": "id"},
	0x0902: {"entity": "cast", "field": "text", "writable": true, "args": "id"},
	0x0903: {"entity": "cast", "field": "fontStyle", "writable": true, "args": "id"},
	0x0904: {"entity": "cast", "field": "font", "writable": true, "args": "id"},
	0x0905: {"entity": "cast", "field": "lineHeight", "writable": true, "args": "id"},
	0x0906: {"entity": "cast", "field": "alignment", "writable": true, "args": "id"},
	0x0907: {"entity": "cast", "field": "fontSize", "writable": true, "args": "id"},
	0x0908: {"entity": "cast", "field": "picture", "writable": true, "args": "id"},
	0x0909: {"entity": "cast", "field": "hilite", "writable": true, "args": "id"},
	0x090A: {"entity": "cast", "field": "number", "writable": true, "args": "id"},
	0x090B: {"entity": "cast", "field": "size", "writable": true, "args": "id"},
	0x0911: {"entity": "cast", "field": "foreColor", "writable": true, "args": "id"},
	0x0912: {"entity": "cast", "field": "backColor", "writable": true, "args": "id"},
	0x0913: {"entity": "cast", "field": "type", "writable": true, "args": "id"},
	0x0A03: {"entity": "chunk", "field": "fontStyle", "writable": true, "args": "chunk"},
	0x0A04: {"entity": "chunk", "field": "font", "writable": true, "args": "chunk"},
	0x0A05: {"entity": "chunk", "field": "lineHeight", "writable": true, "args": "chunk"},
	0x0A07: {"entity": "chunk", "field": "fontSize", "writable": true, "args": "chunk"},
	0x0A11: {"entity": "chunk", "field": "foreColor", "writable": true, "args": "chunk"},
	0x0B01: {"entity": "field", "field": "name", "writable": true, "args": "id"},
	0x0B02: {"entity": "field", "field": "text", "writable": true, "args": "id"},
	0x0B03: {"entity": "field", "field": "fontStyle", "writable": true, "args": "id"},
	0x0B04: {"entity": "field", "field": "font", "writable": true, "args": "id"},
	0x0B05: {"entity": "field", "field": "lineHeight", "writable": true, "args": "id"},
	0x0B06: {"entity": "field", "field": "alignment", "writable": true, "args": "id"},
	0x0B07: {"entity": "field", "field": "fontSize", "writable": true, "args": "id"},
	0x0B09: {"entity": "field", "field": "hilite", "writable": true, "args": "id"},
	0x0B11: {"entity": "field", "field": "foreColor", "writable": true, "args": "id"},
	0x0C03: {"entity": "chunk", "field": "fontStyle", "writable": true, "args": "chunk"},
	0x0C04: {"entity": "chunk", "field": "font", "writable": true, "args": "chunk"},
	0x0C05: {"entity": "chunk", "field": "lineHeight", "writable": true, "args": "chunk"},
	0x0C07: {"entity": "chunk", "field": "fontSize", "writable": true, "args": "chunk"},
	0x0C11: {"entity": "chunk", "field": "foreColor", "writable": true, "args": "chunk"},
	0x0D0C: {"entity": "cast", "field": "loop", "writable": true, "args": "id"},
	0x0D0D: {"entity": "cast", "field": "duration", "writable": true, "args": "id"},
	0x0D0E: {"entity": "cast", "field": "controller", "writable": true, "args": "id"},
	0x0D0F: {"entity": "cast", "field": "directToStage", "writable": true, "args": "id"},
	0x0D10: {"entity": "cast", "field": "sound", "writable": true, "args": "id"},
}


## The row for a bank and its first stack argument, or `{}`.
##
## `{}` is a real answer rather than a failure: banks 0x02 and 0x03 are the menus,
## which this port has no node for at all, and a decoder is expected to emit an
## `unknown_the` node for them rather than guess. Failing the handler instead
## would lose every other statement in it.
static func row(bank: int, first_arg: int) -> Dictionary:
	return ROWS.get((bank << 8) | first_arg, {})
